version: '3.8'

services:
  base_image:
    build:
      context: .
      dockerfile: backend/Dockerfile.base
    image: smarkets-base-image

  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: odds_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - backend_network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend_network

  scraper:
    build:
      context: .
      dockerfile: backend/scraper/Dockerfile
    container_name: scraper
    restart: always
    depends_on:
      - base_image
      - db
      - redis
    environment:
      POSTGRES_DB: odds_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ODDS_PUBLISH_INTERVAL: 0.1
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app/backend
    networks:
      - backend_network

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db
  #   networks:
  #     - backend_network


networks:
  backend_network: